export const USER_CLIENT = 'USER_CLIENT';
export const NOTIFICATION_CLIENT = 'NOTIFICATION_CLIENT';
export const AUTH_CLIENT = 'AUTH_CLIENT';
export const ADMIN_CLIENT = 'ADMIN_CLIENT';
export const BLOG_CLIENT = 'BLOG_CLIENT';
export const API_GATEWAY_CLIENT = 'API_GATEWAY_CLIENT';

export const USER_QUEUE = 'USER_QUEUE';
export const NOTIFICATION_QUEUE = 'NOTIFICATION_QUEUE';
export const AUTH_QUEUE = 'AUTH_QUEUE';
export const ADMIN_SERVICE_QUEUE = 'ADMIN_SERVICE_QUEUE';
export const BLOG_SERVICE_QUEUE = 'BLOG_SERVICE_QUEUE';
export const API_GATEWAY_QUEUE = 'API_GATEWAY_QUEUE';
